try:
    # codigo que pode causar um erro 
    resultado = 10 / 0
except:
    # codigo que trata o erro 
    print("Ocorreu um erro durante a operação!")